# -*- python -*-

import os

Import('env')

env.Append(CPPPATH = ['include', 'source/Irrlicht/zlib', 'source/Irrlicht/jpeglib', 'source/Irrlicht/libpng'] )
env.Append(CPPDEFINES = {'IRRLICHT_EXPORTS':1} )
env.Append(CPPDEFINES = ['PNG_THREAD_UNSAFE_OK', 'PNG_NO_MMX_CODE', 'PNG_NO_MNG_FEATURES'] )

libIrrlicht = env.Library('Irrlicht',
                          Glob('source/Irrlicht/*.cpp') + Glob('source/Irrlicht/lzma/*.c') +
                          Glob('source/Irrlicht/zlib/*.c') + Glob('source/Irrlicht/jpeglib/*.c') +
                          Glob('source/Irrlicht/libpng/*.c') + Glob('source/Irrlicht/aesGladman/*.cpp') +
                          Glob('source/Irrlicht/bzip2/*.c'))

Return('libIrrlicht')
